exclude_patterns:
  - rasa/core/utils.py # codeclimate has some encoding issues with this files because of emojis
  - .*
  - .github/
  - CHANGELOG.mdx
  - CODEOWNERS
  - CODE_OF_CONDUCT.md
  - Dockerfile
  - LICENSE.txt
  - Makefile
  - NOTICE
  - PRONCIPLES.md
  - binder/
  - changelog/
  - data/
  - docs/
  - poetry.lock
  - pyproject.toml
  - tests/
  - stubs/
  - scripts/
  - security.txt
  - secrets.tar.enc
checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-count:
    enabled: false
